### PR TITLE
add_windows_logging_template

### PR DESCRIPTION
**Pull request by marcelschlapfer**
Add Windows Logging Template to nri-nginx

### CODE REVIEW

**Comment by paologallinaharbur** [comment]
I triggered the pre-release tests [here](https://github.com/newrelic/nri-nginx/actions/runs/3249092564)

**Comment by paologallinaharbur** [comment]
Hello @marcelschlapfer the [pre-release failed](https://github.com/newrelic/nri-nginx/actions/runs/3249092564/jobs/5331275939)

> `The Feature element contains an unexpected child element 'ComponentRed'` 

Can you take a look and ping me when we need to trigger again the tests?

**Comment by paologallinaharbur** [comment]
Hello, running again the action -> https://github.com/newrelic/nri-nginx/actions/runs/3263443307

**Comment by paologallinaharbur** [comment]
I failed again:
```
   ⨯ release failed after 75.49s error=failed to find files to archive: globbing failed for pattern nginx-win-log.yml.example: matching "./nginx-win-log.yml.example": file does not exist
```

[Here are the logs](https://github.com/newrelic/nri-nginx/actions/runs/3265482482/jobs/5367835730#step:4:333), I guess there are still issues with the filename

**Comment by paologallinaharbur** [comment]
Running the pre-release again! let's see!

**Comment by marcelschlapfer** [comment]
Updated fix_archives.sh.  HOPEFULLY, that's the last thing.

**Comment by paologallinaharbur** [comment]
[here](https://github.com/newrelic/nri-nginx/actions/runs/3282135332) it is 😄 Let's see if tests passes

**Comment by marcelschlapfer** [comment]
Please try again now.  Added:
<ComponentGroupRef Id="PluginLogConfigsComponent"/>

I looked at the Apache PR I did and it seems this is missing there too, yet that one was merged?  I'm assuming we need to go back and fix it there as well right?
https://github.com/newrelic/nri-apache/pull/79

**Comment by marcelschlapfer** [comment]
PR for the Apache Update: https://github.com/newrelic/nri-apache/pull/80/files

**Review by paologallinaharbur — APPROVED** [review]
Thanks for adding it :)

**Pull request merged**
