### PR TITLE
Mention that logs can be collected

### PR DESCRIPTION
**Pull request by rkbodenner**

### CODE REVIEW

**Comment by kang-makes** [comment]
Hi @rkbodenner,

Technically no. We bundle a file as a sample file that points how to configure fluentbit to grab also Nginx logs. The integration only scrapes and sends metrics to the agent, it does not forward any log.

**Comment by rkbodenner** [comment]
@kang-makes I see how that's technically correct for this repo... but I'm concerned that people who see this repo will not understand that they can get nginx logs if they use our integration.

Isn't Fluent Bit bundled with the agent? Our docs state that this is the case. And the integration is installed via the agent, again according to our docs.

Could you suggest a way to say that the integration, bundled with the agent and configured with our sample config file, forwards logs?

**Comment by kang-makes** [comment]
Hi @rkbodenner,

I would maybe add that the integration package includes sample configuration files to configure this integration and sample files to configure logging forwarding using fluentbit.

That is not only technically correct but allows you to set lots of links to the different documentation patches for infra-agent configuration. logging configuration and such.

What I would avoid is to explicitly say "the integration forward logs" because that could cause false expectations on the user.

**Comment by mangulonr** [comment]
Can we say something similar to "you can gather NGINX logs by...."?
They don't need to know the details under the hood but the value we can give to them.

**Comment by kang-makes** [comment]
Closing this PR as stale. Please reopen this PR when you are ready to retake a look at it.

Thank you for your contribution!

**Pull request closed without merging**
